# Generated by Django 4.1.4 on 2023-01-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1998-04-15'),
            preserve_default=False,
        ),
    ]
